Repository glotzerlab/freud, pull requests merged in 2019-12, with the labels that each got.

#558 Use absolute value of z.
  cpp/locality/NeighborQuery.h
Labels: bug

#565 Use heuristic to determine voro++ block sizes based on particle density.
  ChangeLog.md
  cpp/locality/Voronoi.cc
  doc/source/reference/credits.rst
Labels: enhancement

#564 Update docs about query modes.
  ChangeLog.md
  doc/source/reference/credits.rst
  doc/source/topics/querying.rst
  freud/density.pyx
  freud/environment.pyx
  freud/errors.py
  freud/locality.pyx
  freud/util.pyx
Labels: documentation

#566 Fix/pmftxyz query orientations
  ChangeLog.md
  cpp/pmft/PMFTXY.cc
  cpp/pmft/PMFTXYZ.cc
  cpp/pmft/PMFTXYZ.h
  doc/source/reference/credits.rst
  freud/pmft.pyx
  setup.cfg
  tests/test_pmft.py
Labels: bug, pmft
