Repository glotzerlab/freud, pull requests merged in 2019-06, with the labels that each got.

#290 Refactored convert array
  freud/box.pyx
  freud/cluster.pyx
  freud/common.py
  freud/density.pyx
  freud/environment.pyx
  freud/interface.pyx
  freud/locality.pyx
  freud/msd.pyx
  freud/order.pyx
  freud/pmft.pyx
  tests/test_common.py
Labels: enhancement

#277 Changed timing method to use timeit module
  benchmarks/benchmark.py
Labels: enhancement, testing & validation

#298 Always call setNumThreads at import time
  freud/parallel.pyx
  tests/test_parallel.py
Labels: bug

#306 Using Eigen for diagonalization
  cpp/environment/LocalDescriptors.cc
  cpp/order/NematicOrderParameter.cc
  cpp/util/HOOMDMatrix.cc
  cpp/util/HOOMDMatrix.h
  cpp/util/diagonalize.cc
  cpp/util/diagonalize.h
  setup.py
  tests/test_order_Nematic.py
Labels: enhancement

#307 Refactoring convert array
  cpp/order/NematicOrderParameter.h
  cpp/util/BiMap.h
  freud/box.pyx
  freud/cluster.pyx
  freud/common.py
  freud/density.pyx
  freud/environment.pyx
  freud/interface.pyx
  freud/locality.pyx
  freud/msd.pyx
  freud/order.pyx
  freud/pmft.pyx
  tests/test_common.py
  tests/test_locality_NeighborList.py
Labels: enhancement

#302 Defined _repr_png_ for some modules
  freud/cluster.pyx
  freud/density.pyx
  freud/environment.pyx
  freud/msd.pyx
  freud/plot.py
  freud/pmft.pyx
  freud/voronoi.pyx
  tests/test_cluster.py
  tests/test_density_ComplexCF.py
  tests/test_density_FloatCF.py
  tests/test_density_RDF.py
  tests/test_environment_MatchEnv.py
  tests/test_pmft.py
  tests/test_voronoi.py
Labels: enhancement

#309 Verify values have been computed
  ChangeLog.md
  doc/source/environment.rst
  freud/cluster.pyx
  freud/common.pxd
  freud/common.py
  freud/common.pyx
  freud/density.pyx
  freud/environment.pyx
  freud/interface.pyx
  freud/msd.pyx
  freud/order.pyx
  freud/plot.py
  freud/pmft.pyx
  freud/voronoi.pyx
  tests/test_cluster.py
  tests/test_density_ComplexCF.py
  tests/test_density_FloatCF.py
  tests/test_density_GaussianDensity.py
  tests/test_density_LocalDensity.py
  tests/test_density_RDF.py
  tests/test_environment_AngularSeparation.py
  tests/test_environment_BondOrder.py
  tests/test_environment_LocalBondProjection.py
  tests/test_environment_LocalDescriptors.py
  tests/test_environment_MatchEnv.py
  tests/test_interface.py
  tests/test_msd_MSD.py
  tests/test_order_Cubatic.py
  tests/test_order_HexOrderParameter.py
  tests/test_order_LocalQl.py
  tests/test_order_LocalWl.py
  tests/test_order_Nematic.py
  tests/test_order_RotationalAutocorrelation.py
  tests/test_order_SolLiq.py
  tests/test_order_TransOrderParameter.py
  tests/test_pmft.py
  tests/test_voronoi.py
Labels: enhancement

#251 Add support for pyfftw in MSD
  freud/box.cpp
  freud/cluster.cpp
  freud/common.cpp
  freud/density.cpp
  freud/environment.cpp
  freud/index.cpp
  freud/interface.cpp
  freud/locality.cpp
  freud/msd.cpp
  freud/msd.pyx
  freud/order.cpp
  freud/parallel.cpp
  freud/pmft.cpp
  freud/voronoi.cpp
Labels: enhancement, msd

#317 Wrapper class for tbb::enumerable_thread_specific
  ChangeLog.md
  cpp/density/CorrelationFunction.cc
  cpp/density/CorrelationFunction.h
  cpp/density/GaussianDensity.cc
  cpp/density/GaussianDensity.h
  cpp/density/RDF.cc
  cpp/density/RDF.h
  cpp/environment/BondOrder.cc
  cpp/environment/BondOrder.h
  cpp/order/LocalQl.cc
  cpp/order/LocalQl.h
  cpp/pmft/PMFT.cc
  cpp/pmft/PMFT.h
  cpp/pmft/PMFTR12.cc
  cpp/pmft/PMFTXY2D.cc
  cpp/pmft/PMFTXYT.cc
  cpp/pmft/PMFTXYZ.cc
  cpp/util/ThreadStorage.h
  freud/density.pyx
  tests/test_density_GaussianDensity.py
Labels: bug, enhancement

#311 Added atleast and squeeze for box functions / Moved operations on multiple vectors logic to C++
  cpp/box/Box.h
  freud/_box.pxd
  freud/box.pyx
Labels: enhancement

#323 Fixed segfault in chained NeighborQuery API
  freud/locality.pxd
  freud/locality.pyx
  tests/test_locality_NeighborQuery.py
Labels: bug

#324 Stabilize benchmark and add dealloc
  benchmarks/benchmark.py
  benchmarks/benchmarker.py
  cpp/order/CubaticOrderParameter.h
  freud/box.pyx
  freud/density.pyx
  freud/order.pyx
Labels: bug, enhancement

#318 Feature/repr png more
  .circleci/config.yml
  ChangeLog.md
  doc/source/cluster.rst
  doc/source/conf.py
  doc/source/density.rst
  doc/source/environment.rst
  doc/source/msd.rst
  doc/source/order.rst
  doc/source/pmft.rst
  doc/source/voronoi.rst
  freud/cluster.pyx
  freud/common.pyx
  freud/density.pyx
  freud/environment.pyx
  freud/msd.pyx
  freud/order.pyx
  freud/plot.py
  freud/pmft.pyx
  freud/voronoi.pyx
  tests/test_density_GaussianDensity.py
  tests/test_order_LocalQl.py
  tests/test_order_LocalWl.py
Labels: enhancement

#300 Reduced code duplication in PMFT and RDF
  benchmarks/benchmark_PMFT_PMFTR12.py
  benchmarks/benchmark_PMFT_PMFTXY2D.py
  benchmarks/benchmark_PMFT_PMFTXYT.py
  benchmarks/benchmark_PMFT_PMFTXYZ.py
  cpp/density/RDF.cc
  cpp/density/RDF.h
  cpp/pmft/PMFT.cc
  cpp/pmft/PMFT.h
  cpp/pmft/PMFTR12.cc
  cpp/pmft/PMFTXY2D.cc
  cpp/pmft/PMFTXYT.cc
  cpp/pmft/PMFTXYZ.cc
  cpp/util/Index1D.h
  cpp/util/NdHistogram.cc
  cpp/util/NdHistogram.h
  setup.py
Labels: enhancement, pmft

#329 Remove saru from Cubatic class, it is initialized and used by each thread.
  cpp/order/CubaticOrderParameter.cc
  cpp/order/CubaticOrderParameter.h
Labels: bug

#321 Feature/parallelize sol liq
  ChangeLog.md
  cpp/order/SolLiq.cc
  cpp/order/SolLiq.h
Labels: enhancement, order, performance

#242 Steinhardt class: A new single class for the Steinhardt order Parameter
  cpp/order/Steinhardt.cc
  cpp/order/Steinhardt.h
  freud/_order.pxd
  freud/box.cpp
  freud/cluster.cpp
  freud/density.cpp
  freud/environment.cpp
  freud/locality.cpp
  freud/order.cpp
  freud/order.pyx
  freud/pmft.cpp
  tests/test_order_Steinhardt.py
Labels: enhancement, order

#304 Refactor/voronoi
  cpp/locality/Voronoi.cc
  cpp/locality/Voronoi.h
  freud/_locality.pxd
  freud/cluster.cpp
  freud/density.cpp
  freud/environment.cpp
  freud/interface.cpp
  freud/locality.cpp
  freud/locality.pxd
  freud/locality.pyx
  freud/order.cpp
  freud/pmft.cpp
  freud/voronoi.cpp
  tests/test_locality_Voronoi.py
Labels: enhancement, locality, voronoi
