Repository glotzerlab/freud, pull requests merged in 2019-05, with the labels that each got.

#259 Update README.md
  README.md
Labels: documentation, enhancement

#270 Fix type of y_max argument in PMFTXY2D.
  ChangeLog.md
  freud/_pmft.pxd
  tests/test_pmft.py
Labels: bug

#254 Fix/test precision
  cpp/order/NematicOrderParameter.cc
  tests/test_box_Box.py
  tests/test_common.py
  tests/test_density_ComplexCF.py
  tests/test_density_FloatCF.py
  tests/test_density_RDF.py
  tests/test_environment_AngularSeparation.py
  tests/test_environment_LocalBondProjection.py
  tests/test_environment_MatchEnv.py
  tests/test_locality_NearestNeighbors.py
  tests/test_msd_MSD.py
  tests/test_order_HexOrderParameter.py
  tests/test_order_LocalQl.py
  tests/test_order_Nematic.py
  tests/test_order_RotationalAutocorrelation.py
  tests/test_order_TransOrderParameter.py
  tests/test_pmft.py
  tests/test_voronoi.py
Labels: bug, testing & validation

#256 Use constant memoryviews to prevent errors with read-only inputs.
  ChangeLog.md
  doc/source/installation.rst
  freud/box.pyx
  freud/cluster.pyx
  freud/density.pyx
  freud/environment.pyx
  freud/interface.pyx
  freud/locality.pxd
  freud/locality.pyx
  freud/order.pyx
  freud/pmft.pyx
  tests/test_box_ParticleBuffer.py
  tests/test_density_RDF.py
  tests/test_environment_LocalDescriptors.py
  tests/test_environment_MatchEnv.py
  tests/test_interface.py
  tests/test_msd_MSD.py
  tests/test_order_LocalQl.py
  tests/test_pmft.py
Labels: bug

#257 __repr__ and __str__ methods for pretty representations, Part 2
  ChangeLog.md
  cpp/order/RotationalAutocorrelation.cc
  cpp/order/TransOrderParameter.h
  freud/_order.pxd
  freud/box.pyx
  freud/environment.pyx
  freud/index.pyx
  freud/interface.pyx
  freud/msd.pyx
  freud/order.pyx
  freud/pmft.pyx
  freud/voronoi.pyx
  tests/test_box_Box.py
  tests/test_box_ParticleBuffer.py
  tests/test_cluster.py
  tests/test_density_ComplexCF.py
  tests/test_density_FloatCF.py
  tests/test_density_GaussianDensity.py
  tests/test_density_LocalDensity.py
  tests/test_density_RDF.py
  tests/test_environment_AngularSeparation.py
  tests/test_environment_BondOrder.py
  tests/test_environment_LocalBondProjection.py
  tests/test_environment_LocalDescriptors.py
  tests/test_environment_MatchEnv.py
  tests/test_index.py
  tests/test_interface.py
  tests/test_msd_MSD.py
  tests/test_order_Cubatic.py
  tests/test_order_HexOrderParameter.py
  tests/test_order_LocalQl.py
  tests/test_order_LocalWl.py
  tests/test_order_Nematic.py
  tests/test_order_RotationalAutocorrelation.py
  tests/test_order_SolLiq.py
  tests/test_order_TransOrderParameter.py
  tests/test_pmft.py
  tests/test_voronoi.py
Labels: enhancement

#273 Removed print statement.
  tests/test_environment_BondOrder.py
Labels: bug, testing & validation

#276 Provide instructions for installing dependencies via conda-forge, fix CodeCov badge in docs.
  doc/source/index.rst
  doc/source/installation.rst
Labels: documentation

#275 Add --DEBUG option to Cython.
  .gitignore
  setup.py
Labels: testing & validation

#282 Removed redundant function description
  doc/source/parallel.rst
Labels: 1.0, documentation

#284 LinkCell computes cell neighbors on need basis
  cpp/locality/LinkCell.cc
  cpp/locality/LinkCell.h
Labels: enhancement, locality

#288 Use NumPy arrays for more return types in Box.
  freud/box.pyx
  tests/test_box_Box.py
Labels: enhancement

#292 Fix/remove extra cpp includes
  ChangeLog.md
  cpp/box/Box.cc
  cpp/box/ParticleBuffer.h
  cpp/cluster/Cluster.h
  cpp/density/CorrelationFunction.h
  cpp/density/GaussianDensity.h
  cpp/density/LocalDensity.h
  cpp/density/RDF.h
  cpp/environment/AngularSeparation.h
  cpp/environment/BondOrder.cc
  cpp/environment/BondOrder.h
  cpp/environment/LocalBondProjection.h
  cpp/environment/LocalDescriptors.cc
  cpp/environment/LocalDescriptors.h
  cpp/environment/MatchEnv.h
  cpp/locality/AABB.h
  cpp/locality/AABBQuery.cc
  cpp/locality/AABBQuery.h
  cpp/locality/AABBTree.h
  cpp/locality/LinkCell.cc
  cpp/locality/LinkCell.h
  cpp/locality/NearestNeighbors.cc
  cpp/locality/NearestNeighbors.h
  cpp/locality/NeighborQuery.h
  cpp/order/CubaticOrderParameter.cc
  cpp/order/CubaticOrderParameter.h
  cpp/order/HexOrderParameter.h
  cpp/order/LocalQl.h
  cpp/order/NematicOrderParameter.cc
  cpp/order/NematicOrderParameter.h
  cpp/order/RotationalAutocorrelation.h
  cpp/order/SolLiq.h
  cpp/order/TransOrderParameter.h
  cpp/pmft/PMFT.h
  cpp/pmft/PMFTR12.cc
  cpp/pmft/PMFTR12.h
  cpp/pmft/PMFTXY2D.cc
  cpp/pmft/PMFTXY2D.h
  cpp/pmft/PMFTXYT.cc
  cpp/pmft/PMFTXYT.h
  cpp/pmft/PMFTXYZ.cc
  cpp/pmft/PMFTXYZ.h
  cpp/util/BiMap.h
  cpp/util/TensorMath.h
  doc/source/environment.rst
  freud/_environment.pxd
  freud/environment.pyx
  setup.py
  tests/test_environment_LocalDescriptors.py
Labels: building & installation, enhancement
