Repository glotzerlab/freud, pull requests merged in 2019-02, with the labels that each got.

#222 Fix ReadTheDocs
  .readthedocs.yml
  environment.yml
  readthedocs.yml
Labels: bug, documentation

#220 AngularSeparation, LocalDescriptors docfixes
  freud/environment.cpp
  freud/environment.pyx
Labels: documentation

#223 Fix syntax highlighting in RTD docs
  .readthedocs.yml
  doc/readthedocs-env.yml
Labels: bug, documentation

#221 Bugfixes in LocalQl, LocalQlNear, LocalWl, LocalWlNear
  cpp/order/LocalWl.cc
  cpp/order/LocalWl.h
  freud/order.cpp
  freud/order.pyx
  tests/test_order_LocalQl.py
  tests/test_order_LocalWl.py
Labels: bug, order
