Repository glotzerlab/freud, pull requests merged in 2019-07, with the labels that each got.

#334 Next: remove freud.index module.
  doc/source/indexer.rst
  doc/source/modules.rst
  freud/__init__.py
  freud/_box.pxd
  freud/_cluster.pxd
  freud/_density.pxd
  freud/_environment.pxd
  freud/_locality.pxd
  freud/_order.pxd
  freud/_pmft.pxd
  freud/box.pyx
  freud/cluster.pyx
  freud/density.pyx
  freud/environment.pyx
  freud/index.pyx
  freud/interface.pyx
  freud/locality.pyx
  freud/order.pyx
  freud/pmft.pyx
  freud/util.pxd
  freud/util/_Index1D.pxd
  freud/util/__init__.cpp
  freud/util/__init__.pxd
  freud/util/__init__.py
  freud/voronoi.pyx
  setup.py
  tests/test_index.py
Labels: enhancement

#333 Fix cubatic replicates.
  ChangeLog.md
  cpp/order/CubaticOrderParameter.cc
  cpp/order/CubaticOrderParameter.h
  freud/_order.pxd
  freud/order.pyx
Labels: bug

#339 Improve docstring for MSD
  freud/msd.pyx
Labels: documentation, msd

#336 Documentation corrections for LocalBondProjection and LocalDensity.
  doc/source/images/density.png
  doc/source/images/gen_density_graphic.py
  freud/environment.pyx
Labels: documentation

#295 Added functional API to loop over neighbors
  cpp/cluster/Cluster.cc
  cpp/cluster/Cluster.h
  cpp/density/CorrelationFunction.cc
  cpp/density/CorrelationFunction.h
  cpp/density/LocalDensity.cc
  cpp/density/RDF.cc
  cpp/density/RDF.h
  cpp/environment/BondOrder.cc
  cpp/environment/BondOrder.h
  cpp/environment/MatchEnv.cc
  cpp/locality/AABBQuery.cc
  cpp/locality/AABBQuery.h
  cpp/locality/LinkCell.cc
  cpp/locality/LinkCell.h
  cpp/locality/NearestNeighbors.cc
  cpp/locality/NeighborBond.h
  cpp/locality/NeighborComputeFunctional.h
  cpp/locality/NeighborList.cc
  cpp/locality/NeighborList.h
  cpp/locality/NeighborQuery.cc
  cpp/locality/NeighborQuery.h
  cpp/locality/Voronoi.cc
  cpp/locality/Voronoi.h
  cpp/order/HexOrderParameter.cc
  cpp/order/LocalQl.cc
  cpp/order/SolLiq.cc
  cpp/order/SolLiq.h
  cpp/order/TransOrderParameter.cc
  cpp/pmft/PMFTR12.cc
  cpp/pmft/PMFTR12.h
  cpp/pmft/PMFTXY2D.cc
  cpp/pmft/PMFTXY2D.h
  cpp/pmft/PMFTXYT.cc
  cpp/pmft/PMFTXYT.h
  cpp/pmft/PMFTXYZ.cc
  cpp/pmft/PMFTXYZ.h
  cpp/util/NdHistogram.h
  extern/dset/LICENSE.txt
  extern/dset/README.md
  extern/dset/dset.h
  freud/_cluster.pxd
  freud/_density.pxd
  freud/_environment.pxd
  freud/_locality.pxd
  freud/_pmft.pxd
  freud/cluster.pyx
  freud/density.pyx
  freud/environment.pyx
  freud/locality.pxd
  freud/locality.pyx
  freud/pmft.pyx
  setup.py
  tests/test_cluster.py
  tests/test_density_ComplexCF.py
  tests/test_density_FloatCF.py
  tests/test_environment_AngularSeparation.py
  tests/test_environment_BondOrder.py
  tests/test_environment_LocalBondProjection.py
  tests/test_pmft.py
Labels: enhancement

#337 Adding more tests
  tests/test_box_ParticleBuffer.py
  tests/test_density_ComplexCF.py
  tests/test_density_FloatCF.py
  tests/test_density_GaussianDensity.py
  tests/test_density_LocalDensity.py
  tests/test_density_RDF.py
  tests/test_environment_AngularSeparation.py
  tests/test_environment_BondOrder.py
  tests/test_environment_LocalBondProjection.py
  tests/test_environment_LocalDescriptors.py
  tests/test_locality_LinkCell.py
  tests/test_locality_NearestNeighbors.py
  tests/test_locality_NeighborList.py
  tests/test_locality_NeighborQuery.py
  tests/test_locality_Voronoi.py
  tests/test_order_HexOrderParameter.py
  tests/test_order_LocalQl.py
  tests/test_order_LocalWl.py
  tests/test_order_SolLiq.py
  tests/test_order_Steinhardt.py
  tests/test_pmft.py
  tests/test_voronoi.py
  tests/util.py
Labels: help wanted, testing & validation

#350 Opt/rot acorr
  cpp/order/RotationalAutocorrelation.cc
  cpp/order/RotationalAutocorrelation.h
  freud/_order.pxd
  freud/order.pyx
Labels: order

#353 Force Cython rebuild on RTD.
  setup.py
Labels: bug, documentation

#338 Fix LocalQlNear filter
  cpp/order/LocalQl.cc
  cpp/order/Steinhardt.cc
  freud/density.cpp
  freud/environment.cpp
  freud/locality.cpp
  freud/order.cpp
  freud/order.pyx
  freud/pmft.cpp
  tests/test_order_LocalQl.py
  tests/test_order_LocalWl.py
  tests/test_order_Steinhardt.py
Labels: bug, order

#351 Test/cf nn
  freud/density.pyx
  tests/test_density_ComplexCF.py
  tests/test_density_FloatCF.py
Labels: enhancement, testing & validation

#352 Test/localdescriptors
  tests/test_environment_LocalDescriptors.py
  tests/util.py
Labels: testing & validation

#357 Fix issue with multiple computes of LocalQl
  ChangeLog.md
  cpp/order/LocalQl.cc
  tests/test_order_LocalQl.py
Labels: bug, order

#358 Fix/update steinhardt neighbors
  ChangeLog.md
  cpp/order/LocalQl.cc
  cpp/order/LocalQl.h
  cpp/order/Steinhardt.cc
  cpp/order/Steinhardt.h
  tests/test_order_Steinhardt.py
Labels: bug

#354 Fix/duplicate cell shells
  cpp/locality/LinkCell.cc
  cpp/locality/LinkCell.h
  tests/test_locality_NeighborQuery.py
Labels: bug

#342 More Neighbor Query iteration.
  cpp/density/LocalDensity.cc
  cpp/density/LocalDensity.h
  cpp/environment/AngularSeparation.cc
  cpp/environment/LocalBondProjection.cc
  cpp/environment/LocalDescriptors.cc
  cpp/locality/LinkCell.cc
  cpp/locality/NearestNeighbors.cc
  cpp/locality/NeighborBond.h
  cpp/locality/NeighborComputeFunctional.cc
  cpp/locality/NeighborComputeFunctional.h
  cpp/locality/NeighborList.cc
  cpp/locality/NeighborQuery.h
  cpp/order/HexOrderParameter.cc
  cpp/order/HexOrderParameter.h
  cpp/order/HexTransOrderParameter.cc
  cpp/order/HexTransOrderParameter.h
  cpp/order/Steinhardt.cc
  cpp/order/Steinhardt.h
  cpp/order/TransOrderParameter.cc
  cpp/order/TransOrderParameter.h
  cpp/pmft/PMFT.h
  cpp/pmft/PMFTXY2D.cc
  freud/_density.pxd
  freud/_locality.pxd
  freud/_order.pxd
  freud/density.pyx
  freud/interface.pyx
  freud/locality.pyx
  freud/order.pyx
  freud/pmft.pyx
  setup.py
  tests/test_cluster.py
  tests/test_density_ComplexCF.py
  tests/test_density_FloatCF.py
  tests/test_density_LocalDensity.py
  tests/test_density_RDF.py
  tests/test_environment_BondOrder.py
  tests/test_environment_LocalBondProjection.py
  tests/test_environment_LocalDescriptors.py
  tests/test_locality_NeighborQuery.py
  tests/test_order_HexOrderParameter.py
  tests/test_order_Steinhardt.py
  tests/test_order_TransOrderParameter.py
  tests/test_pmft.py
  tests/util.py
Labels: enhancement

#360 Changed cf signature to take in NeighborBond
  cpp/cluster/Cluster.cc
  cpp/density/CorrelationFunction.cc
  cpp/density/RDF.cc
  cpp/environment/BondOrder.cc
  cpp/locality/NeighborComputeFunctional.h
  cpp/pmft/PMFTR12.cc
  cpp/pmft/PMFTXY2D.cc
  cpp/pmft/PMFTXYT.cc
  cpp/pmft/PMFTXYZ.cc
  cpp/util/NdHistogram.h
Labels: enhancement
