Repository glotzerlab/freud, pull requests merged in 2020-06, with the labels that each got.

#595 Updated citation information.
  doc/source/reference/citing.rst
  freud/__init__.py
Labels: documentation

#631 Use non-broken build of ld_impl_linux-64 for ReadTheDocs.
  doc/readthedocs-env.yml
Labels: bug

#625 Doc/add examples
  ChangeLog.md
  doc/source/reference/credits.rst
  freud/box.pyx
  freud/cluster.pyx
  freud/density.pyx
  freud/environment.pyx
  freud/order.pyx
  tests/test_doctests.py
Labels: documentation, enhancement
