Repository glotzerlab/freud, pull requests merged in 2020-05, with the labels that each got.

#607 Replace undef min/max with a preprocessor definition.
  cpp/environment/AngularSeparation.cc
  cpp/environment/MatchEnv.cc
  cpp/locality/AABB.h
  cpp/locality/LinkCell.cc
  cpp/order/RotationalAutocorrelation.cc
  cpp/order/Wigner3j.cc
  cpp/util/utils.h
  setup.py
Labels: bug, building & installation

#609 Update Sphinx environment due to conflict with jupyter_sphinx.
  doc/readthedocs-env.yml
Labels: bug, documentation

#608 Fix parameter checking for Cubatic.
  ChangeLog.md
  cpp/order/Cubatic.cc
  cpp/order/Cubatic.h
  doc/source/reference/credits.rst
  freud/_order.pxd
  freud/order.pyx
  tests/test_order_Cubatic.py
Labels: bug, order

#620 Fixed broken link to compiling from source
  README.rst
Labels: documentation

#612 Added more metadata to setup.py.
  setup.py
Labels: documentation

#621 Improve developer docs on building/writing documentation
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  doc/source/conf.py
  doc/source/gettingstarted/installation.rst
  doc/source/reference/development/howtoadd.rst
Labels: documentation

#613 Refactor/pmft tests
  doc/source/reference/credits.rst
  tests/test_pmft.py
Labels: pmft, testing & validation

#618 Add weighted feature to Hexatic.
  ChangeLog.md
  cpp/order/HexaticTranslational.cc
  cpp/order/HexaticTranslational.h
  doc/source/reference/credits.rst
  freud/_order.pxd
  freud/data.py
  freud/order.pyx
  freud/plot.py
  tests/test_box_Box.py
  tests/test_cluster.py
  tests/test_density_CorrelationFunction.py
  tests/test_density_GaussianDensity.py
  tests/test_density_RDF.py
  tests/test_environment_MatchEnv.py
  tests/test_locality_NeighborQuery.py
  tests/test_locality_Voronoi.py
  tests/test_msd_MSD.py
  tests/test_order_Hexatic.py
  tests/test_order_SolidLiquid.py
  tests/test_order_Steinhardt.py
  tests/test_pmft.py
Labels: enhancement, order

#615 Fix/pmftxyt orientation
  ChangeLog.md
  cpp/pmft/PMFT.h
  cpp/pmft/PMFTR12.cc
  cpp/pmft/PMFTR12.h
  cpp/pmft/PMFTXY.cc
  cpp/pmft/PMFTXY.h
  cpp/pmft/PMFTXYT.cc
  cpp/pmft/PMFTXYT.h
  cpp/pmft/PMFTXYZ.cc
  cpp/pmft/PMFTXYZ.h
  doc/source/reference/credits.rst
  freud/pmft.pyx
  tests/test_pmft.py
Labels: bug, pmft

#614 Fix/pmft normalization
  ChangeLog.md
Labels: bug, pmft
