Repository glotzerlab/freud, pull requests merged in 2020-09, with the labels that each got.

#653 Add Cython pyx, pxd, pxi files to MANIFEST.in
  ChangeLog.md
  MANIFEST.in
Labels: bug, building & installation

#619 Fix/pmftxyz eq ors normalization
  cpp/pmft/PMFTXYZ.cc
  cpp/pmft/PMFTXYZ.h
  tests/test_pmft.py
Labels: bug, pmft

#656 Fix missing angle bracket in link.
  doc/source/topics/querying.rst
Labels: documentation

#658 Add newlines after example blocks to fix Sphinx rendering.
  freud/box.pyx
  freud/cluster.pyx
  freud/density.pyx
  freud/environment.pyx
  freud/order.pyx
Labels: documentation
