Repository glotzerlab/freud, pull requests merged in 2020-01, with the labels that each got.

#568 update document of center_of_mass in box.pyx
  freud/box.pyx
Labels: documentation

#570 Docs revisions from paper reviews
  README.rst
  freud/locality.pyx
Labels: documentation

#572 Remove redundant function definition from PMFT
  cpp/box/Box.h
  cpp/environment/BondOrder.cc
  cpp/locality/BondHistogramCompute.h
  cpp/pmft/PMFT.h
  cpp/pmft/PMFTR12.cc
  cpp/pmft/PMFTXY.cc
  cpp/pmft/PMFTXYT.cc
  cpp/pmft/PMFTXYZ.cc
Labels: refactor

#574 Add minor clarifying documentation to AABBQuery
  doc/source/reference/freud.bib
  freud/locality.pyx
Labels: documentation

#581 Add option to limit number of neighbor bonds in LocalDescriptors
  ChangeLog.md
  cpp/environment/LocalDescriptors.cc
  cpp/environment/LocalDescriptors.h
  cpp/locality/NeighborBond.h
  cpp/locality/NeighborList.cc
  cpp/locality/NeighborList.h
  cpp/locality/NeighborQuery.h
  freud/_environment.pxd
  freud/_locality.pxd
  freud/environment.pyx
  freud/locality.pyx
  tests/test_locality_NeighborList.py
Labels: bug, enhancement
