Repository glotzerlab/freud, pull requests merged in 2021-04, with the labels that each got.

#753 Fix arXiv links
  ChangeLog.md
  doc/source/reference/credits.rst
  doc/source/reference/freud.bib
Labels: documentation

#746 Build wheels with cibuildwheel.
  .circleci/ci-oldest-reqs.txt
  .circleci/config.yml
  .circleci/deploy-linux.sh
  .circleci/deploy-macos.sh
  .github/dependabot.yml
  .github/workflows/build_wheels.yml
  .github/workflows/cibuildwheel-before-build.ps1
  .github/workflows/cibuildwheel-before-build.sh
  .github/workflows/cibuildwheel-before-test.ps1
  .github/workflows/cibuildwheel-before-test.sh
  .gitignore
  CMakeLists.txt
  freud/CMakeLists.txt
  pyproject.toml
  requirements/requirements-test.txt
  setup.py
Labels: building & installation, enhancement

#754 Shorten tests
  tests/test_density_GaussianDensity.py
  tests/test_density_LocalDensity.py
  tests/test_density_RDF.py
Labels: performance, testing & validation
